name: build

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version
        run: |
          # Default tag as commit SHA
          VERSION=${GITHUB_SHA::7}

          # Use tag name if it's a tag push
          if [ "$GITHUB_EVENT_NAME" == "push" ] && [ "$GITHUB_REF_TYPE" == "tag" ]; then
            VERSION=${GITHUB_REF_NAME}
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: mode=max
          tags: "ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.VERSION }}"